### ISSUE TITLE
Handling tuple of operations

### ISSUE THREAD

**Issue by marcsarfa** [spotify/pythonflow#21]
This gives the following error: `TypeError: not all arguments converted during string formatting`
```python
def f(z):
    return z, z

with pf.Graph() as g:
    x = pf.placeholder('x')
    y = f(x)
    
g([y], x=1)
```

However this works:
```python
def f(z):
    return z, z

def tuple_op(x, y):
    return x, y

with pf.Graph() as g:
    x = pf.placeholder('x')
    y = pf.func_op(tuple_op, *f(x))
    
g([y], x=1)
```
and it outputs `((1, 1),)`

It seems that pythonflow does not know how to handle properly tuples of operations. It could be useful to compute easily a tuple of operations, for example when one wants to define parts of the graph in an auxiliary function as above.
Adding a `@pf.opmethod()` decorator does not work if there are pythonflow operations in the function. It raises the error `ValueError: 'graph' must be given explicitly or a default graph must be set
` since it encapsulates an operation inside another operation.

**Comment by tillahoffmann** [comment]
Yes, we should handle some built-in collections such as tuples, lists, and dictionaries better. #18 is caused by the same underlying issue because complex slicing implicitly constructs a `slice` instance whose elements are not evaluated.

Currently, we [attempt to evaluate an object as an operation if it is not already available in the context](https://github.com/spotify/pythonflow/blob/master/pythonflow/core.py#L297). But we should check whether an object is a collection whose members are operations and evaluate its constituents as well.

**Comment by tillahoffmann** [comment]
@marcsarfa, #22 will support your use case but not quite the code you have presented above.

```python
with pf.Graph() as g:
    x = pf.constant('x')
    y = (x, x)
g([y])  # ValueError: '(<pf.func_op 'd5078acccf174b6fb5e4ba31ff5321b0' target=<function identity at 0x1088d5158> args=<1 items> kwargs=<0 items>>, <pf.func_op 'd5078acccf174b6fb5e4ba31ff5321b0' target=<function identity at 0x1088d5158> args=<1 items> kwargs=<0 items>>)' is not an `Operation` instance or operation name
```

But

```python
with pf.Graph() as g:
    x = pf.constant('x')
    y = pf.identity((x, x))
g([y])  # (('x', 'x'),)
```
